#!/usr/bin/env bash
# Compose unified BC FLA Separation Agreement JSON Schema from sub-schemas
# Inputs: schema/00-toplevel.json, schema/02-parties.json ... schema/07-validity.json
# Outputs: schema/agreement.schema.json (unified), schema/types.ts, schema/sample-filled.json

set -euo pipefail
DIR="/Users/mjb/Desktop/family-law-settlement-poc"
cd "$DIR"

extract_json() {
  local src="$1"
  local dst="$2"
  # GC.AI wraps JSON in ```json fences sometimes, sometimes returns raw JSON
  jq -r '.result' "$src" > "/tmp/gcai-raw-$$.txt"
  if grep -q '```json' "/tmp/gcai-raw-$$.txt"; then
    sed -n '/```json/,/```/p' "/tmp/gcai-raw-$$.txt" | sed '1d;$d' > "$dst"
  elif grep -q '```' "/tmp/gcai-raw-$$.txt"; then
    sed -n '/```/,/```/p' "/tmp/gcai-raw-$$.txt" | sed '1d;$d' > "$dst"
  else
    cp "/tmp/gcai-raw-$$.txt" "$dst"
  fi
  rm -f "/tmp/gcai-raw-$$.txt"
  # Validate
  if ! jq empty "$dst" 2>/dev/null; then
    echo "WARN: $dst is not valid JSON; saving for manual review" >&2
    return 1
  fi
  return 0
}

echo "=== Extracting JSON from GC.AI responses ==="
for n in 02 03 04 05 06 07; do
  src="gcai-responses/$n-"*.json
  src=$(ls $src 2>/dev/null | head -1)
  if [[ -z "$src" || ! -s "$src" ]]; then
    echo "MISSING: $n response not yet ready"
    continue
  fi
  base=$(basename "$src" .json)
  dst="schema/$base.json"
  if extract_json "$src" "$dst"; then
    echo "  $n -> $dst ($(wc -c < $dst) bytes)"
  fi
done

echo ""
echo "=== Composing unified schema ==="
# Build the unified schema by merging properties from each sub-schema
jq -n '
  {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://justack.ai/schemas/bc-fla-separation-agreement/v1",
    "title": "BC Family Law Act — Separation Agreement Parameters",
    "description": "Comprehensive JSON Schema for parameters of a separation agreement governed by the Family Law Act, S.B.C. 2011, c. 25. Generated by InstructIT POC, 2026-04-24, with GC.AI-drafted sub-schemas. All [VERIFY] markers indicate substantive items requiring counsel review before client deployment.",
    "type": "object",
    "version": "0.1.0-poc",
    "generated_at": (now | todate),
    "sources": [
      "Top-level structure: gcai-responses/01-toplevel.json",
      "Parties: gcai-responses/02-parties.json",
      "Parenting: gcai-responses/03-parenting.json",
      "Property: gcai-responses/04-property.json",
      "Support: gcai-responses/05-support.json",
      "Standard clauses: gcai-responses/06-standard.json",
      "Validity: gcai-responses/07-validity.json"
    ],
    "definitions": {},
    "properties": {},
    "required": []
  }' > schema/agreement.schema.json.tmp

# Merge each sub-schema's properties + definitions
for f in schema/02-parties.json schema/03-parenting.json schema/04-property.json schema/05-support.json schema/06-standard.json schema/07-validity.json; do
  [[ ! -s "$f" ]] && { echo "skip missing $f"; continue; }
  jq --slurpfile sub "$f" '
    .definitions = (.definitions + ($sub[0].definitions // {})) |
    .properties = (.properties + ($sub[0].properties // {})) |
    .required = (.required + ($sub[0].required // []) | unique)
  ' schema/agreement.schema.json.tmp > schema/agreement.schema.json.tmp2
  mv schema/agreement.schema.json.tmp2 schema/agreement.schema.json.tmp
done

mv schema/agreement.schema.json.tmp schema/agreement.schema.json
echo "Unified schema written: $(wc -c < schema/agreement.schema.json) bytes"
echo "  Definitions: $(jq '.definitions | length' schema/agreement.schema.json)"
echo "  Properties: $(jq '.properties | length' schema/agreement.schema.json)"

echo ""
echo "=== Counting [VERIFY] markers ==="
grep -c "VERIFY" schema/agreement.schema.json || true

echo ""
echo "=== Done ==="
echo "Files:"
ls -la schema/
